#!/bin/bash
# Last line tape recorder v0.4 - fullscreen viewer for multiple files inside tar archives
# 2014-2016 (c) Kurashov A.K., under GNU GPLv3

# void new line before EOF
function vnlbeof {
	perl -pe 'chomp if eof'
}

function go_back {
	CUR_PTR=$(($CUR_PTR-$1))
	if [ "$CUR_PTR" -lt 0 ]; then
		CUR_PTR=$MAX_PTR
	fi
}

function go_forward {
	CUR_PTR=$(($CUR_PTR+$1))
	if [ "$CUR_PTR" -gt "$MAX_PTR" ]; then
		CUR_PTR=0
	fi
}

function print_prompt {
	echo -e "-= Last line tape recorder v0.2 =-\n\nImage ID: $CUR_PTR , Total images: $(($MAX_PTR + 1))"
	if [ "$#" -gt 0 ]; then
		echo "$1"
	fi
}

function show_info {
	print_prompt
	read -N 1 ttyin
}

function goto_id {
	print_prompt "Go to ID?"
	read NEW_PTR
	if [ "$NEW_PTR" -gt "$CUR_PTR" ]; then
		go_forward $(($NEW_PTR-$CUR_PTR))
	else
		go_back $(($CUR_PTR-$NEW_PTR))
	fi
}

function showgfx {
		if [ "$TERMCST" != "KOI8-R" ]; then
		tar Oxvf $2 $1 | iconv -c -f koi8-r -t $TERMCST | vnlbeof
		else
		tar Oxvf $2 $1 | vnlbeof
		fi
		read -N 1 ttyin
}

# arguments check
if [ "$#" -lt 1 ]; then
	echo "usage: lastlinetaperecorder file"
	exit
fi
#
TERMCST=`echo "$LANG" | sed 's/^.*\.//'`
if [ "$TERMCST" == ""]; then
	TERMCST="ascii";
fi
CUR_PTR=0
readarray -t filename MAX_PTR < <(tar -tf "$1")
MAX_PTR=$((${#filename[@]} - 1))
# infinite navigation loop
while [ 1 ] ; do
	clear
	# view file
	showgfx ${filename[$CUR_PTR]} $1
	clear
	# process user input
	case "$ttyin" in
		# back
		"h" )
		go_back 1
		;;
		# back jump
		"j" )
		go_back 10
		;;
		# forward
		"l" )
		go_forward 1
		;;
		# forward jump
		"k" )
		go_forward 10
		;;
		# show info
		"i" )
		show_info ${filename[$CUR_PTR]}
		;;
		# go to new id
		"g" )
		goto_id
		;;
		# quit
		"q" )
		exit
	esac
done
clear
